INSERT INTO review_rating (review_id, rating, review_text, resource_id_fk,username)
VALUES (1, 4,
        'The meeting room was great, clean and spacious. The equipment provided was in good working condition. Highly recommended!',
        1,"amal"),
       (2, 3,
        'The cubicle was a bit cramped, but it was still functional. It would be better if it had more space and a little bit of privacy.',
        2,"kamal"),
       (3, 5,
        'The conference room was amazing! It had all the necessary equipment for our presentation, and the view from the window was breathtaking. Definitely booking it again.',
        3,"Namal"),
       (4, 2,
        'The meeting room was not up to the mark. The table and chairs were old and uncomfortable. The lighting was poor too.',
        4,"ramal"),
       (5, 4,
        'The cubicle was good enough for my needs. It was clean and had enough space for my work. The noise level was also manageable.',
        5,"bimal"),
       (6, 3,
        'The conference room was decent, but the projector was not working properly. It was a bit distracting during our presentation.',
        6,"Asan"),
       (7, 5,
        'The meeting room was perfect for our team''s brainstorming session. It had a lot of natural light and a comfortable seating arrangement. Highly recommend it!',
        1,"nisan"),
       (8, 2,
        'The cubicle was not clean, and the chair was broken. It was hard to focus on work with all the noise around.',
        2,"malshan"),
       (9, 4,
        'The conference room was spacious and had a good ambiance. The temperature was just right, and the chairs were comfortable.',
        3,"chathupa"),
       (10, 5,
        'The meeting room was fantastic. It had all the necessary equipment, and the chairs were very comfortable. The staff was also very accommodating.',
        4,"naveen"),
       (11, 3, 'The cubicle was not great, but it was sufficient for my needs. It could use some improvements, though.',
        5,"lasal"),
       (12, 4,
        'The conference room was good, but it was a bit too warm. The chairs were comfortable, and the staff was very helpful.',
        6,"nuwan"),
       (13, 5,
        'The meeting room was excellent. It had everything we needed, and the staff was very attentive. The coffee was also great!',
        1,"hasini"),
       (14, 2, 'The cubicle was a disaster. It was dirty and cramped, and the noise level was unbearable.', 2,"thisai"),
       (15, 4,
        'The conference room was perfect for our needs. It had all the necessary equipment, and the staff was very accommodating.',
        3,"apsara"),
       (16, 5,
        'The meeting room was spacious and well-lit. The chairs were comfortable, and the staff was very friendly.', 4,"manavi"),
       (17, 3, 'The cubicle was functional, but it could use some improvements. The noise level was also a bit high.',
        5,"theeja"),
       (18, 4,
        'The conference room was clean and had a good ambiance. The chairs were comfortable, and the staff was very helpful.',
        6,"nuwani"),
       (19, 5,
        'The meeting room was amazing! It had all the necessary equipment, and the staff went above and beyond to make our event a success.',
        1,"aravindi"),
       (20, 2, 'The cubicle was in a noisy area, and the chair was uncomfortable. It was hard to focus on work.', 2,"keethaki")

